name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: false

      - name: Ensure at least one commit exists
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Initial commit" || echo "No changes to commit"

      - name: Ensure branch exists
        run: |
          git branch -M main
          git push origin main || echo "Branch already exists"

      - name: Ignore large files
        run: git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch 'Rag_Documents/layout-parser-paper.pdf'" HEAD || echo "No files to remove"

      - name: Debug authentication
        run: echo "Token length: ${#HF_TOKEN}"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin "https://RizwanRizwan:${HF_TOKEN}@huggingface.co/spaces/RizwanRizwan/langgraph-project-lifecycle"
          git push --force origin main
